// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {orchestrator} from '../models';
import {context} from '../models';

export function Cancel():Promise<void>;

export function Generate(arg1:orchestrator.GenerationParams):Promise<void>;

export function GetImageData():Promise<string>;

export function GetProgress():Promise<number>;

export function GetState():Promise<string>;

export function ListModels():Promise<Array<string>>;

export function Start(arg1:context.Context):Promise<void>;
