// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['orchestrator']['Manager']['CancelJob'](arg1);
}

export function CancelRunningJob() {
  return window['go']['orchestrator']['Manager']['CancelRunningJob']();
}

export function ClearCompleted() {
  return window['go']['orchestrator']['Manager']['ClearCompleted']();
}

export function EnqueueJob(arg1) {
  return window['go']['orchestrator']['Manager']['EnqueueJob'](arg1);
}

export function GetImageData() {
  return window['go']['orchestrator']['Manager']['GetImageData']();
}

export function GetProgress() {
  return window['go']['orchestrator']['Manager']['GetProgress']();
}

export function GetQueue() {
  return window['go']['orchestrator']['Manager']['GetQueue']();
}

export function GetState() {
  return window['go']['orchestrator']['Manager']['GetState']();
}

export function GetSystemStats() {
  return window['go']['orchestrator']['Manager']['GetSystemStats']();
}

export function ListLoras() {
  return window['go']['orchestrator']['Manager']['ListLoras']();
}

export function ListModels() {
  return window['go']['orchestrator']['Manager']['ListModels']();
}

export function ReorderQueue(arg1, arg2) {
  return window['go']['orchestrator']['Manager']['ReorderQueue'](arg1, arg2);
}

export function RetryJob(arg1) {
  return window['go']['orchestrator']['Manager']['RetryJob'](arg1);
}

export function Start(arg1) {
  return window['go']['orchestrator']['Manager']['Start'](arg1);
}
