// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['orchestrator']['Manager']['Cancel']();
}

export function Generate(arg1) {
  return window['go']['orchestrator']['Manager']['Generate'](arg1);
}

export function GetImageData() {
  return window['go']['orchestrator']['Manager']['GetImageData']();
}

export function GetProgress() {
  return window['go']['orchestrator']['Manager']['GetProgress']();
}

export function GetState() {
  return window['go']['orchestrator']['Manager']['GetState']();
}

export function GetSystemStats() {
  return window['go']['orchestrator']['Manager']['GetSystemStats']();
}

export function ListLoras() {
  return window['go']['orchestrator']['Manager']['ListLoras']();
}

export function ListModels() {
  return window['go']['orchestrator']['Manager']['ListModels']();
}

export function Start(arg1) {
  return window['go']['orchestrator']['Manager']['Start'](arg1);
}
